//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LanguageDetector.rc

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#define TEXTFILE 255
#define LANGUAGE_DETECTOR_WORDLIST_DA 256
#define LANGUAGE_DETECTOR_WORDLIST_DE 257
#define LANGUAGE_DETECTOR_WORDLIST_EN 258
#define LANGUAGE_DETECTOR_WORDLIST_ES 259
#define LANGUAGE_DETECTOR_WORDLIST_FR 260
#define LANGUAGE_DETECTOR_WORDLIST_IT 261
#define LANGUAGE_DETECTOR_WORDLIST_NB 262
#define LANGUAGE_DETECTOR_WORDLIST_PL 263
#define LANGUAGE_DETECTOR_WORDLIST_PT 264
#define LANGUAGE_DETECTOR_WORDLIST_SV 265
